### ISSUE TITLE
What happened to the repo?

### ISSUE THREAD

**Issue by dogunbound** [damnitharshit/wallpapers#2]
I decided to look for your repo and I was no longer starred to it. I could still do a git pull, so I looked on the website, and now you only have 7 stars (as of 7/23/24). Not only that, but I was no longer starred to the repo! What happened to the repo? I remember you having 100+ stars last time I checked.

**Comment by damnitharshit** [comment]
You are right, I used to have 100+ stars on this repo.

The original repo had become too big to clone (for me atleast) and this bugged me a lot so I ended up deleting the original and restarting...which meant losing the star count, but what's the point of having an un-cloneable repo, I thought.

Sorry about the inconvenience caused!

**Comment by dogunbound** [comment]
No inconvenience. Same url, so a git pull still works. Just curious what happened. I love that you are still maintaining it. Love the new pictures!
